# Generated by Django 5.2 on 2025-04-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domla',
            fields=[
                ('domla_id', models.AutoField(primary_key=True, serialize=False)),
                ('ismi', models.CharField(blank=True, max_length=50, null=True)),
                ('yoshi', models.SmallIntegerField()),
                ('ish_staji', models.SmallIntegerField()),
                ('lavozimi', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('fan_id', models.AutoField(primary_key=True, serialize=False)),
                ('fan_nomi', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('guruh_id', models.AutoField(primary_key=True, serialize=False)),
                ('guruh_nomi', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('unver_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomi', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomlaFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domla_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.domla')),
                ('fan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.fanlar')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('talaba_id', models.AutoField(primary_key=True, serialize=False)),
                ('ismi', models.CharField(blank=True, max_length=50, null=True)),
                ('yoshi', models.SmallIntegerField()),
                ('kursi', models.SmallIntegerField()),
                ('gurush_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.guruh')),
            ],
        ),
        migrations.CreateModel(
            name='TalabaFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.SmallIntegerField()),
                ('fan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.fanlar')),
                ('talaba_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('yonalish_id', models.AutoField(primary_key=True, serialize=False)),
                ('yonalish_nomi', models.CharField(blank=True, max_length=250, null=True)),
                ('unver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.univer')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='yonalish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.yonalish'),
        ),
    ]
