# Generated by Django 5.2 on 2025-04-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talaba',
            old_name='gurush_id',
            new_name='guruh_id',
        ),
        migrations.RemoveField(
            model_name='yonalish',
            name='unver_id',
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('fakultet_id', models.AutoField(primary_key=True, serialize=False)),
                ('fakultet_nomi', models.CharField(blank=True, max_length=250, null=True)),
                ('unver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fakultetlar', to='unver.univer')),
            ],
        ),
        migrations.AddField(
            model_name='yonalish',
            name='fakultet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unver.fakultet'),
        ),
    ]
