# Generated by Django 5.2 on 2025-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unver', '0002_rename_gurush_id_talaba_guruh_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='univer',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
